# =============================================================
# Running-window RM-ANOVA: Consistency x Amplitude
# Generated by 04_stats_anova.ipynb - do not edit by hand
# =============================================================

DATA_PATH    <- "data_for_stats_anova_rw"
STATS_PATH   <- "summaries/stats/anova_running"
EXPERIMENTS  <- c("EX_1", "EX_9", "EX_7", "EX_3")
WIN_CENTERS  <- c(-500, -475, -450, -425, -400, -375, -350, -325, -300, -275, -250, -225, -200, -175, -150, -125, -100, -75, -50, -25, 0, 25, 50, 75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325, 350, 375, 400, 425, 450, 475, 500, 525, 550, 575, 600, 625, 650, 675, 700, 725, 750, 775, 800, 825, 850, 875, 900, 925, 950, 975, 1000)
OUTCOMES     <- c("p_correct_response", "saccade_count_normalized")
MIN_SOUND    <- 5L    # min sound count per subject-cell
MIN_SUBJECTS <- 10L   # min complete-data subjects per window

dir.create(STATS_PATH, recursive = TRUE, showWarnings = FALSE)

# ── extract F/p for one named effect from aov() summary ───
extract_effect <- function(s, effect_name) {
  for (sname in names(s)) {
    tab <- s[[sname]][[1]]
    if (!is.null(tab) && effect_name %in% rownames(tab)) {
      df_num <- as.integer(tab[effect_name, "Df"])
      df_den <- if ("Residuals" %in% rownames(tab))
                  as.integer(tab["Residuals", "Df"]) else NA_integer_
      return(data.frame(
        effect  = effect_name,
        F_value = as.numeric(tab[effect_name, "F value"]),
        p_value = as.numeric(tab[effect_name, "Pr(>F)"]),
        df_num  = df_num,
        df_den  = df_den,
        stringsAsFactors = FALSE
      ))
    }
  }
  data.frame(effect=effect_name, F_value=NA_real_, p_value=NA_real_,
             df_num=NA_integer_, df_den=NA_integer_, stringsAsFactors=FALSE)
}

all_results <- list()
total_wins  <- length(EXPERIMENTS) * length(WIN_CENTERS)
done        <- 0L

for (exp in EXPERIMENTS) {
  fpath <- file.path(DATA_PATH, paste0(exp, "_conditions.csv"))
  if (!file.exists(fpath)) { cat("SKIP", exp, "\n"); next }
  d <- read.csv(fpath, stringsAsFactors = FALSE)
  d$consistency_cat <- factor(d$consistency_cat,
                              levels = c("consistent", "inconsistent"))
  d$amplitude_bin   <- factor(d$amplitude_bin, levels = c(1, 2, 3),
                              labels = c("low", "medium", "high"))
  d$subject         <- factor(d$subject)
  cat(sprintf("\n=== %s  (%d rows) ===\n", exp, nrow(d)))

  for (win_c in WIN_CENTERS) {
    done <- done + 1L
    if (done %% 20 == 0) cat(sprintf("  progress: %d / %d\n", done, total_wins))

    win_data <- d[d$window_center == win_c, ]
    win_data <- win_data[win_data$sound_count >= MIN_SOUND, ]
    if (nrow(win_data) == 0) next

    cell_key     <- paste(win_data$consistency_cat, win_data$amplitude_bin)
    n_cells_subj <- tapply(cell_key, win_data$subject,
                           function(x) length(unique(x)))
    complete_subs <- names(n_cells_subj)[n_cells_subj == 6L]

    for (outcome in OUTCOMES) {
      win_out <- win_data[win_data$subject %in% complete_subs &
                          !is.na(win_data[[outcome]]), ]
      n_cells2 <- tapply(
        paste(win_out$consistency_cat, win_out$amplitude_bin),
        win_out$subject, function(x) length(unique(x)))
      complete_subs2 <- names(n_cells2)[n_cells2 == 6L]
      if (length(complete_subs2) < MIN_SUBJECTS) next
      win_final         <- win_out[win_out$subject %in% complete_subs2, ]
      win_final$subject <- droplevels(win_final$subject)

      tryCatch({
        fml_str <- paste0(outcome,
          " ~ consistency_cat * amplitude_bin + Error(subject/(consistency_cat * amplitude_bin))")
        fit <- aov(as.formula(fml_str), data = win_final)
        s   <- summary(fit)

        for (eff in c("consistency_cat", "amplitude_bin",
                      "consistency_cat:amplitude_bin")) {
          row <- extract_effect(s, eff)
          row$experiment    <- exp
          row$window_center <- win_c
          row$outcome       <- outcome
          row$n_subjects    <- length(complete_subs2)
          all_results[[length(all_results)+1]] <- row
        }
      }, error = function(e) NULL)
    }
  }
}

if (length(all_results) > 0) {
  results_df <- do.call(rbind, all_results)
  out_file   <- file.path(STATS_PATH, "anova_results_running.csv")
  write.csv(results_df, out_file, row.names = FALSE)
  cat(sprintf("\n✓ Saved: %s  (%d rows)\n", out_file, nrow(results_df)))
} else {
  cat("WARNING: No results collected!\n")
}